### ISSUE TITLE
Questions regarding code execution time.

### ISSUE THREAD

**Issue by ma-kjh** [rohitgandikota/erasing-llm#4]
Thanks for your work.

I have a question. When running the WMDP erasing code, the total estimated time is about 50 hours. Did you run it as is? Or is there a way to optimize it?

If you can run it using multi-GPU, can you share the code and script?

Or 

Could you use the pregenerated_consistency_prompts?? if use it, could you share the code for generating consistency_prompts ?

**Comment by rohitgandikota** [comment]
Good question! You can pre-generate consistency code which will make it much much faster. Thanks for catching this

Here is the code for doing that: https://github.com/rohitgandikota/erasing-llm/blob/main/trainscripts/prepare_consistency_data.py

**Comment by ma-kjh** [comment]
Thanks for your quick response.
